apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    # database => index name
    database: 'analytic_event_logs'
    jsonData:
      timeField: '@timestamp'
      esVersion: '7.15.2'
