---
version: '2'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.2
    container_name: filebeat
    mem_limit: 1g
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./apache-logs:/usr/share/filebeat/apache-logs"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    restart: always
    volumes:
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    hostname: kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: always
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - "./kibanadata:/usr/share/kibana/data"

  grafana:
    image: grafana/grafana:8.5.3
    hostname: grafana
    container_name: grafana
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED = false
      - GF_ANALYTICS_CHECK_FOR_UPDATES = false
      - GF_AUTH_ANONYMOUS_ENABLED = true
    volumes:
      - "./grafanadata:/var/lib/grafana"
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/conf/grafana.ini:/etc/grafana/grafana.ini"

networks:
  default:
    external:
      name: kafka-elk-shared-network